In [1]:
import numpy as np

In [2]:
zeroArray = np.zeros(5)

In [3]:
print(zeroArray)

[0. 0. 0. 0. 0.]


In [4]:
a = np.zeros((4,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
print(a.shape)  # Beschreibung der Achsen 
print(a.ndim)   # Anzahl der Array Dimensionen
print(a.size)   # Anzahld der gesamten Elemente
print(a.dtype)  # Datatype

(4, 2)
2
8
float64


In [6]:
# Uninitialized array --> Whatever lies in memory will be written inside
empty_arr = np.empty((4,3))
print(empty_arr)

full_arr = np.full((5,3), 8.4)
print(full_arr)
print(full_arr.dtype)

[[1.15127344e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 9.58114819e+169]
 [1.43700231e-051 2.10581487e-076 1.70252483e-051]
 [4.67105966e-062 1.56116052e+161 1.80195853e+185]]
[[8.4 8.4 8.4]
 [8.4 8.4 8.4]
 [8.4 8.4 8.4]
 [8.4 8.4 8.4]
 [8.4 8.4 8.4]]
float64


In [7]:
# From Python arrays
from_python_arr = np.array([[1, 2, 3, 4], [11, 22, 33, 44]])
print(from_python_arr)

[[ 1  2  3  4]
 [11 22 33 44]]


In [8]:
from_range_arr = np.arange(1,7, 0.4)
print(from_range_arr)
print(from_range_arr.dtype)
print(from_range_arr.shape)

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5.  5.4 5.8 6.2 6.6]
float64
(15,)


In [9]:
# Random Values
np.random.seed(56)

random_array = np.random.rand(4,5)

print(random_array)
print(random_array.dtype)

[[0.98419185 0.33341227 0.67370162 0.19639042 0.35444646]
 [0.81336595 0.24784955 0.45861133 0.87730142 0.39165846]
 [0.32613342 0.09009511 0.83421775 0.0962116  0.64754508]
 [0.54950399 0.84974054 0.26531732 0.44086832 0.88088538]]
float64


In [10]:
# Size in Bytes of each item
print(random_array.itemsize)

8


In [11]:
# Reshaping
# The size must remain the same

range_arr = np.arange(24)
print(range_arr)
print(range_arr.size)
print(range_arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
24
1


In [12]:
range_arr.shape = (6,4)
print(range_arr)
print(range_arr.size)
print(range_arr.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
24
2


In [13]:
# Item access
range_arr[1,2] = 999
print(range_arr)

[[  0   1   2   3]
 [  4   5 999   7]
 [  8   9  10  11]
 [ 12  13  14  15]
 [ 16  17  18  19]
 [ 20  21  22  23]]


In [14]:
# Alle Artithmetischen Operationen funktionieren auch hier
arrit_a = np.array([14, 23, 32, 41])
arrit_b = np.array([5,  4,  3,  2])

sum_a_b = arrit_a + arrit_b
print(sum_a_b)

diff_a_b = arrit_a - arrit_b
print(diff_a_b)

mult_a_b = arrit_a * arrit_b
print(mult_a_b)

[19 27 35 43]
[ 9 19 29 39]
[70 92 96 82]


In [15]:

h = np.arange(5).reshape(1, 1, 5)

print(h)

h_added = h + [10, 20, 30, 40, 50] # same as: h + [[[10, 20, 30, 40, 50]]]

print(h_added)

k = np.arange(4).reshape(2,2)
print(k)
k_added_dummys = k + [100, 200] # same as h + [[100, 200], [100, 200]]
print(k_added_dummys)

[[[0 1 2 3 4]]]
[[[10 21 32 43 54]]]
[[0 1]
 [2 3]]
[[100 201]
 [102 203]]


In [16]:
# Conditionals apply element wise
test_conditional_arr = np.arange(10).reshape((5,2))
print(test_conditional_arr)

print("\n")
greater_4_arr = test_conditional_arr > 4
print(greater_4_arr)
print(greater_4_arr.shape)

print("\n")
only_greater_4 = test_conditional_arr[test_conditional_arr > 3]
print(only_greater_4)
only_greater_reshaped = only_greater_4.reshape(2,3)
print(only_greater_reshaped)

print("\n")
only_dividable_by_two = test_conditional_arr[test_conditional_arr % 2 == 0]
print(only_dividable_by_two)
print(only_dividable_by_two.size)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


[[False False]
 [False False]
 [False  True]
 [ True  True]
 [ True  True]]
(5, 2)


[4 5 6 7 8 9]
[[4 5 6]
 [7 8 9]]


[0 2 4 6 8]
5


In [20]:
a = np.array([[2,6,7],[8,5,2]])
print(a)
print(a.shape)

# Methods calculate over all elements regardless of the array shape
print("mean=", a.mean())
print("max=", a.max())
print("min=", a.min())
print("sum=", a.sum())

[[2 6 7]
 [8 5 2]]
(2, 3)
mean= 5.0
max= 8
min= 2
sum= 30


In [26]:

b = np.arange(24).reshape(2, 3, 4)
print(b)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [27]:
# Calculate Matrix with Matrix
b.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [29]:
# Calculate row-wise
b.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [30]:
# calculate column wise
b.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [ ]:
# universal functions (static in np lib. No Object Method like above)

print(b)

for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    # Example: np.square(b) --> Returns a new np Array
    print(f"\n{func.__name__}")
    print(func(b))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

absolute
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

sqrt
[[[0.         1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974 2.64575131]
  [2.82842712 3.         3.16227766 3.31662479]]

 [[3.46410162 3.60555128 3.74165739 3.87298335]
  [4.         4.12310563 4.24264069 4.35889894]
  [4.47213595 4.58257569 4.69041576 4.79583152]]]

exp
[[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
  [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
  [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]

 [[1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06]
  [8.88611052e+06 2.41549528e+07 6.56599691e+07 1.78482301e+08]
  [4.85165195e+08 1.31881573e+09 3.58491285e+09 9.74480345e+09]]]

log
[[[      -inf 0.         0.69314718 1.09861229]
  [1.38629436 1.60943791 1.79175947 1.94591015

C:\Users\Torst\AppData\Local\Temp\ipykernel_26996\75042772.py:7: RuntimeWarning: divide by zero encountered in log
  print(func(b))


In [ ]:
# binary universal functions to apply on two ndarrays

arr_one = np.array([1, -2, 3, 4])
arr_two = np.array([2, 8, -1, 7])

new_arr = np.add(arr_one, arr_two)

print(new_arr)



[ 3  6  2 11]


In [35]:
np.greater(arr_one, arr_two)

array([False, False,  True, False])

In [36]:
np.maximum(arr_one, arr_two)

array([2, 8, 3, 7])

In [37]:
np.copysign(arr_one, arr_two)

array([ 1.,  2., -3.,  4.])

In [39]:
# multi dimensional index
b_multi = np.arange(48).reshape(4, 12)

print(b_multi)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]]


In [46]:
print(b_multi[1, 3])
print(b_multi[2, :]) # row 3, all columns
print(b_multi[:, 2]) # colum 3, all rows
print(b_multi[0:2, 2:5]) # rows 0 to 2, columns with index 2 to 4
print(b_multi[(0, 2), 2:5]) # rows 0 AND 2, columns with index 2 to 4

15
[24 25 26 27 28 29 30 31 32 33 34 35]
[ 2 14 26 38]
[[ 2  3  4]
 [14 15 16]]
[[ 2  3  4]
 [26 27 28]]


In [ ]:
# Solving scalar equotation
# x is actually x1 and y is actually x2
# so this is basically Ax = b
# A [[2, 6], [5, 3]] --> As vector
# b [6, -9] --> as Vector
# x [x, y] --> as Vectory
# So now lets solve this and calculate x, y with numpy
#2x+6y=6 
#5x+3y=−9
from numpy import linalg

constants = np.array([[2, 6], [5, 3]])
results = np.array([6, -9])

solution = linalg.solve(constants, results)

In [50]:
print(solution)

[-3.  2.]
