In [2]:
import numpy as np

In [3]:
zeroArray = np.zeros(5)

In [4]:
print(zeroArray)

[0. 0. 0. 0. 0.]


In [5]:
a = np.zeros((4,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
print(a.shape)  # Beschreibung der Achsen 
print(a.ndim)   # Anzahl der Array Dimensionen
print(a.size)   # Anzahld der gesamten Elemente
print(a.dtype)  # Datatype

(4, 2)
2
8
float64


In [7]:
# Uninitialized array --> Whatever lies in memory will be written inside
empty_arr = np.empty((4,3))
print(empty_arr)

full_arr = np.full((5,3), 8.4)
print(full_arr)
print(full_arr.dtype)

[[9.82227508e-312 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 1.78022341e-306 1.53553183e-051]
 [7.11402331e-038 1.37103770e-071 4.50045092e+174]
 [1.96826914e+160 1.52885910e+160 9.50770749e+169]]
[[8.4 8.4 8.4]
 [8.4 8.4 8.4]
 [8.4 8.4 8.4]
 [8.4 8.4 8.4]
 [8.4 8.4 8.4]]
float64


In [8]:
# From Python arrays
from_python_arr = np.array([[1, 2, 3, 4], [11, 22, 33, 44]])
print(from_python_arr)

[[ 1  2  3  4]
 [11 22 33 44]]


In [10]:
from_range_arr = np.arange(1,7, 0.4)
print(from_range_arr)
print(from_range_arr.dtype)
print(from_range_arr.shape)

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5.  5.4 5.8 6.2 6.6]
float64
(15,)


In [11]:
# Random Values
np.random.seed(56)

random_array = np.random.rand(4,5)

print(random_array)
print(random_array.dtype)

[[0.98419185 0.33341227 0.67370162 0.19639042 0.35444646]
 [0.81336595 0.24784955 0.45861133 0.87730142 0.39165846]
 [0.32613342 0.09009511 0.83421775 0.0962116  0.64754508]
 [0.54950399 0.84974054 0.26531732 0.44086832 0.88088538]]
float64


In [ ]:
# Size in Bytes of each item
print(random_array.itemsize)

8


In [13]:
# Reshaping
# The size must remain the same

range_arr = np.arange(24)
print(range_arr)
print(range_arr.size)
print(range_arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
24
1


In [16]:
range_arr.shape = (6,4)
print(range_arr)
print(range_arr.size)
print(range_arr.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
24
2


In [17]:
# Item access
range_arr[1,2] = 999
print(range_arr)

[[  0   1   2   3]
 [  4   5 999   7]
 [  8   9  10  11]
 [ 12  13  14  15]
 [ 16  17  18  19]
 [ 20  21  22  23]]


In [20]:
# Alle Artithmetischen Operationen funktionieren auch hier
arrit_a = np.array([14, 23, 32, 41])
arrit_b = np.array([5,  4,  3,  2])

sum_a_b = arrit_a + arrit_b
print(sum_a_b)

diff_a_b = arrit_a - arrit_b
print(diff_a_b)

mult_a_b = arrit_a * arrit_b
print(mult_a_b)

[19 27 35 43]
[ 9 19 29 39]
[70 92 96 82]


In [ ]:

h = np.arange(5).reshape(1, 1, 5)

print(h)

h_added = h + [10, 20, 30, 40, 50] # same as: h + [[[10, 20, 30, 40, 50]]]

print(h_added)

k = np.arange(4).reshape(2,2)
print(k)
k_added_dummys = k + [100, 200] # same as h + [[100, 200], [100, 200]]
print(k_added_dummys)

[[[0 1 2 3 4]]]
[[[10 21 32 43 54]]]
[[0 1]
 [2 3]]
[[100 201]
 [102 203]]


In [39]:
# Conditionals apply element wise
test_conditional_arr = np.arange(10).reshape((5,2))
print(test_conditional_arr)

print("\n")
greater_4_arr = test_conditional_arr > 4
print(greater_4_arr)
print(greater_4_arr.shape)

print("\n")
only_greater_4 = test_conditional_arr[test_conditional_arr > 3]
print(only_greater_4)
only_greater_reshaped = only_greater_4.reshape(2,3)
print(only_greater_reshaped)

print("\n")
only_dividable_by_two = test_conditional_arr[test_conditional_arr % 2 == 0]
print(only_dividable_by_two)
print(only_dividable_by_two.size)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


[[False False]
 [False False]
 [False  True]
 [ True  True]
 [ True  True]]
(5, 2)


[4 5 6 7 8 9]
[[4 5 6]
 [7 8 9]]


[0 2 4 6 8]
5
